[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"


# Proxies for required interfaces
Camera360RGB = "camera360rgb:tcp -h localhost -p 0"
IMU = "imu:tcp -h localhost -p 0"
Lidar3D = "lidar3d:tcp -h localhost -p 0"
OmniRobot = "omnirobot:tcp -h localhost -p 0"
Webots2Robocomp = "webots2robocomp:tcp -h localhost -p 0"

[Endpoints]
# Endpoints for subscriptions interfaces
FullPoseEstimationPubTopic = "tcp -p 0"
FullPoseEstimationPubPrefix = ""



[Agent]
id = 0 # Change id
name = "concept_robot"
configFile = ""

[ViewAgent]
tree = true
graph = true
2d = true
3d = true

[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
